Repository mindsdb/lightwood, pull requests merged in 2020-02, with the labels that each got.

#117 Weight balancing forst booster and accuracy function
  lightwood/__about__.py
  lightwood/api/predictor.py
  lightwood/config/config.py
  lightwood/mixers/boost/boost.py
  lightwood/mixers/nn/nn.py
  tests/ci_tests/ci_tests.py
Labels: enhancement

#119 Learning rate and boosting bugs
  lightwood/__about__.py
  lightwood/api/data_source.py
  lightwood/api/predictor.py
  lightwood/config/config.py
  lightwood/encoders/text/tfidf.py
  lightwood/mixers/boost/boost.py
  lightwood/mixers/helpers/ranger.py
  lightwood/mixers/nn/nn.py
  requirements.txt
  setup.py
Labels: bug, enhancement

#120 Sklearn version update + tests for 3.8
  .travis.yml
  lightwood/__about__.py
  lightwood/mixers/nn/nn.py
  requirements.txt
  requirements_dev.txt
Labels: dependencies

#107 [WIP] Fix lint issues
  lightwood/__about__.py
  lightwood/__init__.py
  lightwood/api/data_source.py
  lightwood/api/gym.py
  lightwood/api/predictor.py
  lightwood/constants/lightwood.py
  lightwood/data_schemas/predictor_config.py
  lightwood/encoders/__init__.py
  lightwood/encoders/categorical/autoencoder.py
  lightwood/encoders/categorical/onehot.py
  lightwood/encoders/datetime/__init__.py
  lightwood/encoders/datetime/datetime.py
  lightwood/encoders/image/__init__.py
  lightwood/encoders/image/helpers/img_to_vec.py
  lightwood/encoders/image/img_2_vec.py
  lightwood/encoders/image/nn.py
  lightwood/encoders/numeric/__init__.py
  lightwood/encoders/numeric/numeric.py
  lightwood/encoders/text/__init__.py
  lightwood/encoders/text/distilbert.py
  lightwood/encoders/text/helpers/infersent.py
  lightwood/encoders/text/helpers/rnn_helpers.py
  lightwood/encoders/text/infersent.py
  lightwood/encoders/text/rnn.py
  lightwood/encoders/time_series/__init__.py
  lightwood/encoders/time_series/cesium_ts.py
  lightwood/mixers/__init__.py
  lightwood/mixers/helpers/debugging.py
  lightwood/mixers/helpers/default_net.py
  lightwood/mixers/helpers/plinear.py
  lightwood/mixers/helpers/ranger.py
  lightwood/mixers/helpers/shapes.py
  lightwood/mixers/helpers/transformer.py
  lightwood/mixers/nn/nn.py
  lightwood/mixers/sk_learn/feature.py
  lightwood/mixers/sk_learn/sk_learn.py
  lightwood/model_building/basic_ax_optimizer/basic_ax_optimizer.py
  scraps/bayesian_nn/bayesian_nn.py
  setup.cfg
Labels: WIP, discussion, refactor

#122 Added some monitoring functionality, will be disabled by default
  lightwood/__about__.py
  lightwood/api/predictor.py
  lightwood/config/config.py
  lightwood/mixers/helpers/debugging.py
  lightwood/mixers/nn/nn.py
  visdom.sh
Labels: enhancement, test

#121 tsFresh time series encoder
  MANIFEST.in
  lightwood/__about__.py
  lightwood/encoders/__init__.py
  lightwood/encoders/audio/amplitude_ts.py
  lightwood/encoders/time_series/__init__.py
  lightwood/encoders/time_series/cesium_ts.py
  lightwood/encoders/time_series/ts_fresh_ts.py
  optional_requirements.txt
  requirements.txt
  setup.py
  tests/ci_tests/ci_tests.py
Labels: enhancement

#123 Improvements to TsFresh Timeseries Encoder
  .travis.yml
  lightwood/__about__.py
  lightwood/encoders/time_series/ts_fresh_ts.py
  requirements.txt
Labels: enhancement
