Repository mindsdb/lightwood, pull requests merged in 2020-07, with the labels that each got.

#204 base encoder
  lightwood/api/predictor.py
  lightwood/encoders/__init__.py
  lightwood/encoders/audio/amplitude_ts.py
  lightwood/encoders/categorical/autoencoder.py
  lightwood/encoders/categorical/onehot.py
  lightwood/encoders/datetime/datetime.py
  lightwood/encoders/encoder_base.py
  lightwood/encoders/image/img_2_vec.py
  lightwood/encoders/image/nn.py
  lightwood/encoders/numeric/numeric.py
  lightwood/encoders/text/distilbert.py
  lightwood/encoders/text/infersent.py
  lightwood/encoders/text/rnn.py
  lightwood/encoders/text/tfidf.py
  lightwood/encoders/time_series/cesium_ts.py
  lightwood/encoders/time_series/rnn.py
  lightwood/encoders/time_series/ts_fresh_ts.py
Labels: refactor

#215 Multiple output categories fix
  lightwood/mixers/nn/nn.py
  tests/ci_tests/ci_tests.py
Labels: bug, enhancement

#224 Rnn test
  lightwood/encoders/__init__.py
  lightwood/encoders/time_series/rnn.py
  tests/unit_tests/encoders/time_series/test_rnn.py
  tests/unit_tests/encoders/time_series/test_ts.py
Labels: test

#227 Encode with flair
  lightwood/api/data_source.py
  lightwood/constants/lightwood.py
  lightwood/encoders/__init__.py
  lightwood/encoders/text/__init__.py
  lightwood/encoders/text/flair.py
  requirements.txt
Labels: enhancement

#213 Improved img_2_vec encoder
  lightwood/encoders/image/helpers/img_to_vec.py
  lightwood/encoders/image/img_2_vec.py
  tests/unit_tests/encoders/images/img_2_vec.py
Labels: bug, refactor, test

#232 Small fixes
  lightwood/encoders/numeric/numeric.py
  tests/unit_tests/encoders/text/test_short_text_encoder.py
Labels: bug, refactor
