Repository mindsdb/lightwood, pull requests merged in 2020-01, with the labels that each got.

#101 K-fold cross validation
  .gitignore
  lightwood/__about__.py
  lightwood/__init__.py
  lightwood/api/data_source.py
  lightwood/api/gym.py
  lightwood/api/predictor.py
  lightwood/config/config.py
  lightwood/encoders/categorical/autoencoder.py
  lightwood/encoders/image/helpers/nn.py
  lightwood/encoders/image/mlp_img/image_0.png
  lightwood/encoders/image/mlp_img/image_1.png
  lightwood/encoders/image/mlp_img/image_2.png
  lightwood/encoders/numeric/numeric.py
  lightwood/encoders/text/distilbert.py
  lightwood/mixers/helpers/default_net.py
  lightwood/mixers/nn/nn.py
  requirements.txt
  tests/ci_tests/full_test.py
Labels: enhancement, refactor

#111 Improvements to Travis
  .travis.yml
Labels: bug, discussion, test

#108 Initial CI tests
  .travis.yml
  lightwood/__about__.py
  lightwood/api/data_source.py
  lightwood/encoders/datetime/datetime.py
  lightwood/encoders/image/img_2_vec.py
  lightwood/encoders/image/nn.py
  lightwood/encoders/text/infersent.py
  lightwood/encoders/text/rnn.py
  tests/ci_tests/ci_tests.py
Labels: WIP, test

#114 Dropout, Windows Install, Tfidf encoder, Audio encoder
  lightwood/__about__.py
  lightwood/api/data_source.py
  lightwood/api/predictor.py
  lightwood/config/config.py
  lightwood/constants/lightwood.py
  lightwood/encoders/__init__.py
  lightwood/encoders/audio/__init__.py
  lightwood/encoders/audio/amplitude_ts.py
  lightwood/encoders/datetime/__init__.py
  lightwood/encoders/image/img_2_vec.py
  lightwood/encoders/image/nn.py
  lightwood/encoders/numeric/numeric.py
  lightwood/encoders/text/__init__.py
  lightwood/encoders/text/distilbert.py
  lightwood/encoders/text/tfidf.py
  lightwood/encoders/time_series/cesium_ts.py
  lightwood/mixers/__init__.py
  requirements.txt
  setup.py
Labels: current priority, dependencies, enhancement, refactor
