Repository mindsdb/lightwood, pull requests merged in 2021-11, with the labels that each got.

#715 Documentation for /most/ lightwood modules
  docssrc/source/analysis.rst
  docssrc/source/api.rst
  docssrc/source/data.rst
  docssrc/source/data/cleaner.rst
  docssrc/source/encoder.rst
  docssrc/source/ensemble.rst
  docssrc/source/helpers.rst
  docssrc/source/index.rst
  docssrc/source/mixer.rst
Labels: documentation

#726 Lgbm GPU hotfix
  .github/workflows/doc_build.yml
  docssrc/README.md
  docssrc/source/index.rst
  lightwood/mixer/lightgbm.py
Labels: Bug

#724 Remove type mapping
  lightwood/api/json_ai.py
  lightwood/api/types.py
  lightwood/encoder/__init__.py
  lightwood/encoder/type_encoder_maps/Array.py
  lightwood/encoder/type_encoder_maps/Audio.py
  lightwood/encoder/type_encoder_maps/Binary.py
  lightwood/encoder/type_encoder_maps/Categorical.py
  lightwood/encoder/type_encoder_maps/Date.py
  lightwood/encoder/type_encoder_maps/Datetime.py
  lightwood/encoder/type_encoder_maps/Float.py
  lightwood/encoder/type_encoder_maps/Image.py
  lightwood/encoder/type_encoder_maps/Integer.py
  lightwood/encoder/type_encoder_maps/Quantity.py
  lightwood/encoder/type_encoder_maps/Rich_Text.py
  lightwood/encoder/type_encoder_maps/Short_Text.py
  lightwood/encoder/type_encoder_maps/Tags.py
  lightwood/encoder/type_encoder_maps/TimeSeries.py
  lightwood/encoder/type_encoder_maps/__init__.py
Labels: refactor

#736 Drop column with no information
  lightwood/helpers/text.py
Labels: enhancement

#722 Documentation for the linear regression
  lightwood/api/types.py
  lightwood/encoder/array/array.py
  lightwood/encoder/categorical/autoencoder.py
  lightwood/encoder/image/img_2_vec.py
  lightwood/encoder/text/pretrained.py
  lightwood/encoder/time_series/rnn.py
  lightwood/mixer/base.py
  lightwood/mixer/lightgbm.py
  lightwood/mixer/lightgbm_array.py
  lightwood/mixer/neural.py
  lightwood/mixer/qclassic.py
  lightwood/mixer/regression.py
  lightwood/mixer/sktime.py
  lightwood/mixer/unit.py
Labels: documentation

#754 Dielectron problems
  lightwood/api/types.py
  lightwood/data/cleaner.py
  lightwood/data/encoded_ds.py
  lightwood/data/timeseries_transform.py
  lightwood/helpers/accuracy.py
  lightwood/helpers/general.py
  tests/integration/advanced/test_timeseries.py
Labels: Bug

#769 OH and Binary Encoders weighting fix
  lightwood/__about__.py
  lightwood/api/json_ai.py
  lightwood/api/types.py
  lightwood/data/statistical_analysis.py
  lightwood/encoder/categorical/binary.py
  lightwood/encoder/categorical/onehot.py
  lightwood/ensemble/best_of.py
Labels: Bug, Fatal Bug, Big Bad Bug

#768 Extend default layout to include GTM scripts
  docssrc/source/_templates/layout.html
Labels: documentation
