Repository mindsdb/lightwood, pull requests merged in 2021-02, with the labels that each got.

#379 Improved DefaultNet shape policy
  lightwood/mixers/helpers/default_net.py
Labels: enhancement

#387 checking for and using gpu
  lightwood/mixers/lightgbm.py
Labels: MONGO, enhancement

#385 Create weights for multiclass
  lightwood/api/data_source.py
Labels: bug
