Repository mindsdb/lightwood, pull requests merged in 2021-09, with the labels that each got.

#501 Refactor: grouped TS splitter into helper function
  lightwood/data/splitter.py
Labels: refactor

#502 Enhanced date-time + tag histograms
  lightwood/data/cleaner.py
  lightwood/data/statistical_analysis.py
  lightwood/helpers/numeric.py
  tests/integration/basic/test_analyze_dataset.py
Labels: Bug

#497 Nonconformist optimizations (for speed)
  lightwood/analysis/explain.py
  lightwood/analysis/nc/icp.py
  lightwood/analysis/nc/nc.py
  lightwood/analysis/nc/wrappers.py
Labels: performance

#500 Make explainer work with categorical targets not present in the training data
  lightwood/analysis/explain.py
  lightwood/analysis/nc/base.py
  lightwood/analysis/nc/icp.py
  lightwood/analysis/nc/util.py
  tests/integration/basic/test_weird_target_dist.py
Labels: Bug

#524 Fix #510 - Sktime dependency
  lightwood/model/sktime.py
  requirements.txt
Labels: dependencies

#534 Rename model to mixer and folds to subsets
  lightwood/analysis/model_analyzer.py
  lightwood/analysis/nc/norm.py
  lightwood/api/encode.py
  lightwood/api/json_ai.py
  lightwood/api/types.py
  lightwood/data/timeseries_analyzer.py
  lightwood/encoder/base.py
  lightwood/encoder/categorical/autoencoder.py
  lightwood/ensemble/base.py
  lightwood/ensemble/best_of.py
  lightwood/helpers/templating.py
  lightwood/mixer/__init__.py
  lightwood/mixer/base.py
  lightwood/mixer/helpers/__init__.py
  lightwood/mixer/helpers/ar_net.py
  lightwood/mixer/helpers/default_net.py
  lightwood/mixer/helpers/ranger.py
  lightwood/mixer/helpers/residual_net.py
  lightwood/mixer/helpers/transform_corss_entropy_loss.py
  lightwood/mixer/lightgbm.py
  lightwood/mixer/lightgbm_array.py
  lightwood/mixer/neural.py
  lightwood/mixer/regression.py
  lightwood/mixer/sktime.py
  lightwood/mixer/unit.py
  lightwood/model/__init__.py
  tests/integration/advanced/test_timeseries.py
  tests/integration/basic/test_categorical.py
  tests/integration/basic/test_model_selection.py
Labels: refactor

#512 Better detection, cleaning and encoding of arrays
  lightwood/api/json_ai.py
  lightwood/data/cleaner.py
  lightwood/data/infer_types.py
  lightwood/data/statistical_analysis.py
  lightwood/encoder/__init__.py
  lightwood/encoder/array/__init__.py
  lightwood/encoder/array/array.py
  lightwood/encoder/time_series/__init__.py
  lightwood/encoder/type_encoder_maps/Array.py
  lightwood/encoder/type_encoder_maps/Binary.py
  lightwood/encoder/type_encoder_maps/Categorical.py
  lightwood/encoder/type_encoder_maps/Date.py
  lightwood/encoder/type_encoder_maps/Datetime.py
  lightwood/encoder/type_encoder_maps/Float.py
  lightwood/encoder/type_encoder_maps/Integer.py
  lightwood/encoder/type_encoder_maps/Quantity.py
  lightwood/encoder/type_encoder_maps/Tags.py
  tests/data/airline_sentiment.csv
  tests/integration/basic/test_airline.py
Labels: Bug, test

#525 Fix #508 - `allow_incomplete_history` for time series predictors
  lightwood/api/json_ai.py
  lightwood/api/types.py
  lightwood/data/timeseries_transform.py
  tests/integration/advanced/test_timeseries.py
Labels: enhancement

#538 Modular Cleaner
  lightwood/api/types.py
  lightwood/data/cleaner.py
  lightwood/data/statistical_analysis.py
  tests/integration/basic/test_weird_target_dist.py
Labels: Bug, J{AI}SON

#499 Add MASE metric to select forecasters
  lightwood/analysis/model_analyzer.py
  lightwood/api/json_ai.py
  lightwood/data/timeseries_analyzer.py
  lightwood/encoder/time_series/helpers/common.py
  lightwood/ensemble/best_of.py
  lightwood/helpers/general.py
  requirements.txt
  tests/unit_tests/data/test_transform_ts.py
Labels: enhancement

#544 Fix for lightgbm device check
  lightwood/mixer/lightgbm.py
Labels: Bug
