Repository mindsdb/lightwood, pull requests merged in 2022-02, with the labels that each got.

#826 Simpler & better Json AI
  .github/workflows/benchmark_check.yml
  docssrc/source/tutorials/custom_mixer/custom_mixer.ipynb
  docssrc/source/tutorials/tutorial_update_models/tutorial_update_models.ipynb
  lightwood/api/__init__.py
  lightwood/api/json_ai.py
  lightwood/api/types.py
  lightwood/helpers/templating.py
  tests/integration/advanced/test_timeseries.py
  tests/integration/basic/test_ensembles.py
  tests/integration/basic/test_model_selection.py
  tests/integration/basic/test_qclassic.py
Labels: enhancement, refactor

#760 Impute missing data inside `cleaner`
  lightwood/api/json_ai.py
  lightwood/api/types.py
  lightwood/data/cleaner.py
  lightwood/helpers/imputers.py
  tests/integration/basic/test_cleaner.py
  tests/unit_tests/data/test_imputers.py
Labels: enhancement

#845 Use Ridge Regression
  lightwood/mixer/regression.py
Labels: Bug
